name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10 # Specify pnpm version used in project (see package.json)

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x' # Specify Node.js version
          cache: 'pnpm'
          cache-dependency-path: 'pcb-app/pnpm-lock.yaml' # Path relative to repo root

      - name: Install dependencies
        working-directory: ./pcb-app # Specify the app directory
        run: pnpm install

      - name: Run Linter
        working-directory: ./pcb-app # Specify the app directory
        run: pnpm lint

      - name: Run Build
        working-directory: ./pcb-app # Specify the app directory
        run: pnpm build 